version: '2'
services:
  web:
    container_name: web
    build: .
    ports: 
      - 8088:80
    volumes: 
      - ./src:/var/www/wellness
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
  
  db: 
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGPASSWORD: password
      POSTGRES_DB: wellness
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres/initdb.d:/docker-entrypoint-initdb.d
      - ./db/postgres/data:/var/lib/postgresql/data